---
# Include variable definitions
- name: "include variable overrides"
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      - "vars/{{ ansible_distrubition }}.yml"
      - "vars/{{ ansible_os_family }}.yml"
      skip: true
  tags:
    - devtools

# Install packages
- name: install devtools packages
  package:
    name: "{{ devtools_packages }}"
    state: "{{ devtools_packages_state }}"
  become: yes
  when: ansible_os_family != 'Archlinux'
  tags:
    - devtools

# Install packages
- name: install devtools packages
  package:
    name: "{{ devtools_packages }}"
    state: "{{ devtools_packages_state }}"
  become: yes
  changed_when: false
  when: ansible_os_family == 'Archlinux'
  tags:
    - devtools
