---
- name: include variable overrides
  include_vars: "{{ item }}"
  vars:
    include_files:
      - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      - "vars/{{ ansible_distribution }}.yml"
      - "vars/{{ ansible_os_family }}.yml"
  loop: "{{ q('first_found', include_files, errors='ignore') }}"

- name: install apt packages
  apt:
    name: "{{ devtools_packages | default(devtools_packages_default) }}"
    state: "{{ devtools_packages_state | default('present') }}"
    update_cache: yes
  become: yes
  when: ansible_os_family == 'Debian'

- name: install yum packages
  yum:
    name: "{{ devtools_packages | default(devtools_packages_default) }}"
    state: "{{ devtools_packages_state | default('present') }}"
    update_cache: yes
  become: yes
  when: ansible_os_family == 'RedHat'

- name: install pacman packages
  pacman:
    name: "{{ devtools_packages | default(devtools_packages_default) }}"
    state: "{{ devtools_packages_state | default('present') }}"
    update_cache: yes
  become: yes
  when: ansible_os_family == 'Archlinux'
