---
- name: Include variable overrides
  ansible.builtin.include_vars: "{{ item }}"
  vars:
    include_files:
      - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      - "vars/{{ ansible_distribution }}.yml"
      - "vars/{{ ansible_os_family }}.yml"
  loop: "{{ q('first_found', include_files, errors='ignore') }}"

- name: Install apt packages
  ansible.builtin.apt:
    name: "{{ devtools_packages | default(devtools_packages_default) }}"
    state: "{{ devtools_packages_state | default('present') }}"
    update_cache: true
  become: true
  when: ansible_os_family == 'Debian'

- name: Install yum packages
  ansible.builtin.yum:
    name: "{{ devtools_packages | default(devtools_packages_default) }}"
    state: "{{ devtools_packages_state | default('present') }}"
    update_cache: true
  become: true
  when: ansible_os_family == 'RedHat'
  tags: skip_ansible_lint

- name: Install pacman packages
  community.general.pacman:
    name: "{{ devtools_packages | default(devtools_packages_default) }}"
    state: "{{ devtools_packages_state | default('present') }}"
    update_cache: true
  become: true
  when: ansible_os_family == 'Archlinux'
