---
# Include variable definitions
- name: "include variable overrides"
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "vars/{{ ansible_distrubition }}.yml"
    - "vars/{{ ansible_os_family }}.yml"
  tags:
    - devtools

# Install packages
- name: install devtools packages
  package: >
    name="{{ devtools_packages }}"
    state="{{ devtools_packages_state }}"
  become: yes
  tags:
    - devtools
