---
- name: include variable overrides
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "vars/{{ ansible_distrubition }}.yml"
        - "vars/{{ ansible_os_family }}.yml"
      skip: true

- name: install apt packages
  apt:
    name: "{{ devtools_packages }}"
    state: "{{ devtools_packages_state }}"
    update_cache: yes
  become: yes
  when: ansible_os_family == 'Debian'

- name: install yum packages
  yum:
    name: "{{ devtools_packages }}"
    state: "{{ devtools_packages_state }}"
    update_cache: yes
  become: yes
  when: ansible_os_family == 'RedHat'

- name: install pacman packages
  pacman:
    name: "{{ item }}"
    state: "{{ devtools_packages_state }}"
    update_cache: yes
  become: yes
  with_items:
    - "{{ devtools_packages }}"
  when: ansible_os_family == 'Archlinux'
